# fronend and backend on node with a mongo db
version: '3'
services:
  db:
    container_name: db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
  backend:
    container_name: Backend
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${BACK_PORT}:${BACK_PORT}
    working_dir: /app/backend
    env_file:
      - .env
    depends_on:
      - db
  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend:/app
  #   working_dir: /app
  #   depends_on:
  #     - backend